[env]
TERM = "xterm-256color"
live_config_reload = "true"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 25
y = 20

[font]
size = 8.0

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[general]
import = [
    "~/dotfiles/terminal/themes/nightfox/extra/carbonfox/alacritty.toml"
]
